---
title: Rickyreticent.Github.Io
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Ricky Anggoro
author: Ricky Anggoro
description: My Personal Blog
avatar: "/images/reverie.png"
footer-links:
  dribbble: 
  email: rickyreticent@gmail.com
  facebook: rickyreticent
  flickr: 
  github: rickyreticent
  instagram: rickyreticent
  linkedin: m-ricky-anggoro-p
  pinterest: 
  rss: rss
  twitter: rickyreticent
  stackoverflow: 
  youtube: 
  googleplus: 
  playconsole: 
disqus: 
google_analytics: 
url: http://rickyreticent.github.io
enforce_ssl: https://rickyreticent.github.io
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jemoji
include:
- _pages
- _uploads
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
