---
title: Rickyreticent.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Ricky Anggoro
author: Amit Merchant
description: An elegant Jekyll theme
avatar: "/reverie/images/reverie.png"
footer-links:
  dribbble: 
  email: amit.d.merchant@gmail.com
  facebook: 
  flickr: 
  github: amitmerchant1990
  instagram: 
  linkedin: 
  pinterest: 
  rss: rss
  twitter: amit_merchant
  stackoverflow: 
  youtube: 
  googleplus: 
  playconsole: 
disqus: 
google_analytics: 
url: http://rickyreticent.github.io
enforce_ssl: https://rickyreticent.github.io
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
include:
- _pages
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
